name: "Waveshare PoE HAT (B)"
description: "PoE HAT Support for Raspberry Pi 3B+ and 4"
version: "1.0.0"
slug: "poe_hat"
init: false
host_network: true
arch:
  - aarch64
devices:
  - /dev/i2c-0
  - /dev/i2c-1
  - /dev/i2c-10
  - /dev/i2c-11
  - /dev/gpiomem
options:
  fan_temp: 43
  brightness: 255
schema:
  fan_temp: int
  brightness: int
